version: "3.7"

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/etc/:/etc/nginx/conf.d
    networks:
      - app

networks:
  app:
    driver: bridge
